#docker-compose.dev.yaml
version: "3.2"
services:
  db:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
  # backend:
  #   build: "./backend"
  #   ports:
  #     - "8080"
  #   depends_on:
  #     - "db"
  # frontend:
  #   build: "./frontend"
  #   ports:
  #     - "3000"
  #   depends_on:
  #     - "backend"
  admin-backend:
    build: "./admin/backend"
    ports:
      - "8080"
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - "db"
  # admin-frontend:
  #   build: "./admin/frontend"
  #   ports:
  #     - "3000"
  #   depends_on:
  #     - "admin-backend"
  nginx:
    build: "./nginx"
    ports:
      - "81:80" 
    volumes:
      - "./frontend/__sapper__/export:/var/www"
    depends_on:
      # - "frontend"
      # - "admin-frontend"
      - "admin-backend"