#docker-compose.yaml
version: "3.6"
services:
  goservice:
    build: "."
    ports:
      - "8080"
  nginx:
    build: "./nginx"
    ports:
      - "81:80"
    volumes:
      - "../static:/var/www"
    depends_on:
      - "goservice"