version: 2 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      # Maybe you need to add some config file specific to circle…

      # - run: cp .circleci/.some-parameter-file .some-parameter-file
      - run: docker-compose up -d
      #- run: docker-compose exec php composer install -n --prefer-dist
      #- run: docker-compose run --rm front yarn install
      #- run: docker-compose run --rm front yarn build
      #- run: docker-compose exec php vendor/bin/phpspec run -vvv
      #- run: docker-compose exec php ./vendor/bin/behat -v